### ISSUE TITLE
V2: Change nationality into an actual reference

### ISSUE THREAD

**Issue by sa-schreiber** [pagemachine/ats#100]
Right now it is a string field containing the country ISO3 (DEU for example).
Reason is legacy compatibility to the old jobmodul system.

Since we pull these codes already from static info tables, the field itself should be a relation to `static_countries` once we can make breaking changes.

**Comment by mbrodala** [comment]
Ich habe einen `2.0.0`-Milestone hierfür angelegt.

**Comment by mbrodala** [comment]
No development here ATM.
