### ISSUE TITLE
Structured Data Tab, Rich Text Editor -> list.

### ISSUE THREAD

**Issue by AKaravas** [pagemachine/ats#113]
By creating a new job, a tab appears which contains a lot information about **Education requirements, Experience requirements, Job benefits** etc.

On most websites, these information are displayed as list, which makes sense, yet the rich text editor doesnt have any list button. 

Would it be possible to add it as well? 

Best regards,

![listbutton](https://user-images.githubusercontent.com/16290719/59349801-d133a680-8d1a-11e9-8622-8912f46ead0d.png)

**Comment by pm-sschreiber** [comment]
Are you sure this is not limited by your website RTE setup? ATS does only use a custom preset for text templates, job RTE fields use the same config as general content (for example, textmedia elements) in your instance.
