### ISSUE TITLE
CSV Export not working in Typo3 8.7

### ISSUE THREAD

**Issue by Melana13** [pagemachine/ats#132]
Getting an error on .CSV Export "Fehler: Datei nicht gefunden" in Typo3 8.7.

I found out that this is because of $GLOBALS['TYPO3_DB'] in ExportService.php which is not supported in Typo3 8.7 anymore.
I have not yet done the migration process described here: https://docs.typo3.org/m/typo3/reference-coreapi/8.7/en-us/ApiOverview/Database/Migration/Index.html

**Comment by mbrodala** [comment]
This should be fixed by now, `$GLOBALS['TYPO3_DB']` is not used here anymore.
