### ISSUE TITLE
PHP error / broken BE if in debug mode

### ISSUE THREAD

**Issue by No5251** [pagemachine/ats#22]
Q | A
-- | --
Bug report? | Yes
Feature request? | No
TYPO3 version | 7.6.23 
Composer mode | No
PHP version | 5.6.32

If debug mode is enabled the backend throws:

> PHP Warning: include(phar:///path/to/htdocs/typo3conf/ext/ats//vendors.phar/vendor/autoload.php): failed to open stream: phar error: invalid url or non-existent phar &quot;phar:///path/to/htdocs/typo3conf/ext/ats//vendors.phar/vendor/autoload.php&quot; in /path/to/typo3temp/Cache/Code/cache_core/ext_localconf_HASH.php line 1551

**Comment by mbrodala** [comment]
I can confirm that the `vendors.phar` is missing in the packages on TER since version 1.0.5, they where present before that. I'll investigate.

**Comment by mbrodala** [comment]
This has been resolved with version 1.1.1, thanks for reporting.
