### ISSUE TITLE
Scheduler cannot find class "DefaultWorkflowConfiguration"

### ISSUE THREAD

**Issue by No5251** [pagemachine/ats#23]
Q | A
-- | --
Bug report? | Yes
Feature request? | No
TYPO3 version | 7.6.23 
Composer mode | No
PHP version | 5.6.32

Scheduler throws:

> PHP Fatal error:  Class 'PAGEmachine\Ats\Workflow\DefaultWorkflowConfiguration' not found in /path/to/htdocs/typo3conf/ext/ats/ext_localconf.php on line 70

**Comment by mbrodala** [comment]
Can you retry after running the `extension:dumpclassloadinginformation` command (or de- and reactivating an arbitrary extension)?

**Comment by mbrodala** [comment]
Please let us know if you still encounter this issue.
