### ISSUE TITLE
Instllation fails on fresh T3 8.7.x LTS

### ISSUE THREAD

**Issue by stefan72** [pagemachine/ats#5]
We installed the ext on a fresh 8.7 system via TER. After the message "ats successfully installed" in the ext manager, the BE throws an error when pressing any new button. The frontend shows the same error. The error was removed by uninstalling the ext. manually on the file server. 

In a second attempt the same error appeared. 

Error BE: Connection Problem
Sorry, but an error occurred while connecting to the server. Please check your network connection.

Error Log: 
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1476107295: PHP Warning: include(phar:///kunden/xxxxx/rp-hosting/xxxx/xxxx/typo3cms/dwwd-8lts/typo3temp/var/Cache/Code/cache_core/vendors.phar/vendor/autoload.php): failed to open stream: phar error: invalid url or non-existent phar &quot;phar:///kunden/xxxxx/rp-hosting/xxxxx/typo3cms/dwwd-8lts/typo3temp/var/Cache/Code/cache_core/vendors.phar/vendor/autoload.php&quot; in /kunden/xxxx/rp-hosting/xxxx/typo3cms/dwwd-8lts/typo3temp/var/Cache/Code/cache_core/ext_localconf_49b958046b13d409f33ce8a52996d2c0fbdc35c2.php line 1503 | TYPO3\CMS\Core\Error\Exception thrown in file /kunden/xxxx/rp-hosting/xxxx/typo3cms/typo3_src-8.7.1/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 106. Requested URL: http://www.dwwd.ch/typo3/index.php?M=system_extinstall&moduleToken=e91f162769caea6b9e571ff240f324f86572d64f 

Any idea what it could be? A bug? 
I set the [SYS][displayErrors] = 1 
But I guess it's not related to this setting?

**Comment by mbrodala** [comment]
Thanks for reporting. From the error message I assume you are using Classic Mode instead of Composer Mode. We'll have a look at this.

**Comment by mbrodala** [comment]
This should be fixed with version 1.0.4, please try that one once it shows up on TER.

**Comment by stefan72** [comment]
Ok, works! Thanks.

**Comment by mbrodala** [comment]
Great, thanks for checking.
