### ISSUE TITLE
Basic documention missing

### ISSUE THREAD

**Issue by stefan72** [pagemachine/ats#6]
It would be favourable to have a documentation to get a basic system running. It's not clear how to set up the job fields Sachbearbeitung, Career and Contact.
![selection_042](https://user-images.githubusercontent.com/12212200/31789739-6507fcb2-b513-11e7-9db4-3cbf41a7351c.png)

**Comment by mbrodala** [comment]
Thanks for your report. Yes, docs in general are on our agenda. :-)

**Comment by pm-sschreiber** [comment]
There is some basic documentation since v1.2, hope this helps: https://docs.typo3.org/typo3cms/extensions/ats/Installation/Index.html#setup

Closing this issue now, if you have further questions just open a new one.
