### ISSUE TITLE
Load extension configuration failed

### ISSUE THREAD

**Issue by karsten0b** [pagemachine/ats#65]
Thanks for the great extension!!! Unfortunately, I get an error message when installing (TYPO3 CMS 8.7.16)

`Detected Fatal Error
require(): Failed opening required 'phar:///home/******/public_html/typo3conf/ext/ats//vendors.phar/vendor/autoload.php' (include_path='.:/opt/cpanel/ea-php71/root/usr/share/pear') in /home/******/public_html/typo3conf/ext/ats/ext_localconf.php on line 192`

If I disable this line, it works. However, I then get the error message "Class 'Symfony \ Component \ Workflow \ DefinitionBuilder' not found" in the backend module. Can you help please?

**Comment by mbrodala** [comment]
What version of the extension did you install? The mentioned `vendors.phar` properly exists in the [package  available in the TER](https://extensions.typo3.org/extension/ats/).

**Comment by karsten0b** [comment]
I have the latest version installed (1.7.0)

**Comment by mbrodala** [comment]
Thanks, does the mentioned file exist on the same level as the `ext_localconf.php`?

Is the [Phar extension](http://php.net/manual/en/book.phar.php) loaded on your server?

**Comment by karsten0b** [comment]
Yes Phar extension is installed. 

[
![bildschirmfoto 2018-07-05 um 13 36 55](https://user-images.githubusercontent.com/17590072/42321238-8deb4538-8058-11e8-96f5-fa0eae5ae505.png)
](url)

**Comment by karsten0b** [comment]
Update. It works on a local machine with same settings. But not with our live system. This is extremely strange, so far we did not have the problems with another extension.

**Comment by mbrodala** [comment]
Can you flush all caches of your instance using the install tool, especially including the PHP opcache?

**Comment by karsten0b** [comment]
Yes, clear all caches works from the install tool. But that does not solve the problem :-(

**Comment by karsten0b** [comment]
The problem has been solved with the new TYPO3 version (8.17). Now everything works as expected;)
