### ISSUE TITLE
Version 1.9.0 does not work on TYPO3 7.6.31

### ISSUE THREAD

**Issue by markusthiel** [pagemachine/ats#91]
Internal Server error

**Comment by mbrodala** [comment]
Can you please add more details? Which kind of page are you loading and what do your (Apache) server logs say?

**Comment by markusthiel** [comment]
Sorry for the delay! No it does not work:


Logs:

GET / HTTP/1.0
(104)Connection reset by peer: mod_fcgid: error reading data from FastCGI server
End of script output before headers: index.php
AH01067: Failed to read FastCGI header
(104)Connection reset by peer: AH01075: Error dispatching request to :

**Comment by mbrodala** [comment]
This looks like an unrelated error with your FastCGI/FPM setup. Please make sure everything is working fine on that front first.

**Comment by markusthiel** [comment]
Everything works fine until i install your extension. no errors in my log before. i can change my apache and my php versions but that doesnt change anything.

**Comment by mbrodala** [comment]
TYPO3v7 is not supported anymore, please create a new ticket if the issue still applies.
